version: "3.8"
services:
  omni-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: omni-tools:custom
    container_name: omni-tools
    restart: unless-stopped
    ports:
      - "3014:80"
